### ISSUE TITLE
[hwameistor UI] Storage Nodes missing "HDD Utilization"

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor-ui#12]
![图片](https://user-images.githubusercontent.com/76234281/230528054-1ca17ca5-fee9-4975-9249-c642bd40d08a.png)
![图片](https://user-images.githubusercontent.com/76234281/230528090-a5b34bfc-01a1-4dc2-89b8-55ea97f9e30b.png)

**Comment by lsq645599166** [comment]
keep the logic same with list page
