### ISSUE TITLE
[hwameistor UI] Migrate Local Volume -- Migrate failed , the reason is empty

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor-ui#16]
![图片](https://user-images.githubusercontent.com/76234281/230565742-8e7e0f03-eab0-404b-91ba-d91d4bef29e9.png)

**Comment by lsq645599166** [comment]
![image](https://user-images.githubusercontent.com/7345199/232410941-eddacef4-392a-4fa5-aff0-1294fb2531ad.png)
using description
