### ISSUE TITLE
[hwameistor-ui] Incorrect interpretation of Local Volumes

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor-ui#23]
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/c6294b71-55c5-46a5-9369-63c06be39583)

**Comment by fangshun-z** [comment]
![image](https://github.com/hwameistor/hwameistor-ui/assets/71168119/c41e090e-412c-4a2a-bcf1-846f7efd7e80)
原型上是这样的啊
