### ISSUE TITLE
[hwameistor UI] need add tips when migrate a lvm

### ISSUE THREAD

**Issue by Vacant2333** [hwameistor/hwameistor-ui#33]
<img width="659" alt="image" src="https://github.com/hwameistor/hwameistor-ui/assets/19872346/aab018d7-3a64-4dd4-ac4c-d698dbe0e0d0">
<img width="1001" alt="image" src="https://github.com/hwameistor/hwameistor-ui/assets/19872346/2bb6a6a2-dc00-4bb9-a418-890785053683">
there is no tips now when i submit this task

**Comment by fangshun-z** [comment]
https://github.com/hwameistor/hwameistor-ui/pull/19
这里已经添加了报错提示了吧
