### ISSUE TITLE
When hwameistor-apiserver is not working properly, some reminder should be displayed on the UI

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor-ui#37]
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/e339fc65-3f8a-489a-ae98-45c792a1ce10)
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/6dcd5fe6-bd3b-4428-9029-634287ca5135)

**Comment by lsq645599166** [comment]
will add a error noty
