### ISSUE TITLE
Available capacity display error

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor-ui#71]
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/4dcba948-35ac-4a59-b610-aecf50999e33)

**Comment by fangshun-z** [comment]
'B' | 'KB' | 'MB' | 'GB' | 'TB' | 'PB' 
Unit B is included in these units, so it can be used for display, right? @FloatXD

**Comment by FloatXD** [comment]
> 'B' | 'KB' | 'MB' | 'GB' | 'TB' | 'PB' Unit B is included in these units, so it can be used for display, right? @FloatXD

i think so
