### ISSUE TITLE
The basic information of the storage node displays errors.

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor-ui#73]
![图片](https://github.com/hwameistor/hwameistor-ui/assets/76234281/392d0ecd-3125-4ccc-a3cc-aa8106318328)

**Comment by fangshun-z** [comment]
<img width="1439" alt="image" src="https://github.com/hwameistor/hwameistor-ui/assets/71168119/2ed0e51f-8758-4871-a382-45222677e331">

**Comment by peng9808** [comment]
Backend has been fixed
