### ISSUE TITLE
[hwameistor UI] The  information in the Storage Pools is not as expected

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/hwameistor-ui#9]
![图片](https://user-images.githubusercontent.com/76234281/230262622-8f71f1df-c4de-4240-a8e0-904cb9359de0.png)

**Comment by lsq645599166** [comment]
![image](https://user-images.githubusercontent.com/7345199/232415072-d75f5617-847a-44f8-ad89-b1c32b45deba.png)

**Comment by Vacant2333** [comment]
Currently, Hwameistor does not provide the attribute of available disk capacity, as it is subject to some limitations, and it will not be offered at this time. We may can remove this column.

**Comment by lsq645599166** [comment]
hide "available disk" column right now
